# Task 1:

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [23]:
def func():
    try:
        n= int(input("Enter a number: "))
        m = 5 / n
        print("\n 5 devided by {} is: {}".format(n,m))
    except:
        print("\n Error... Any number devided by Zero is indefinite.. enter other than zero..")
    

In [24]:
func()

Enter a number: 0

 Error... Any number devided by Zero is indefinite.. enter other than zero..


In [25]:
func()

Enter a number: 2

 5 devided by 2 is: 2.5


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [8]:
subjects = ["Americans", "Indians"] 
verbs =  ["Play", "watch"]
objects = ["Baseball","cricket"]
for s in subjects:
    for v in verbs:
        for o in objects:
            print(s+" "+ v + " " + o)
        

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Task 2:

1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [9]:
import numpy as np
l = [1,2,3,4,5]
l = np.array(l)

def vendor_matrix(vector,n=0,increasing=True):
    if increasing == True:
        print('Vendor Matrix in increasing Order:')
        return np.array([[x**i] for x in l for i in range(n)]).reshape(l.size,n)
    else:
        print('Vendor Matrix in decreasing Order:')
        return np.array([[x**(n-i-1)] for x in l for i in range(n)]).reshape(l.size,n)
        

In [10]:
vendor_matrix(vector=l,n=4,increasing=True)

Vendor Matrix in increasing Order:


array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [11]:
vendor_matrix(vector=l,n=4,increasing=False)

Vendor Matrix in decreasing Order:


array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [12]:
vendor_matrix(vector=l,n=6,increasing=True)

Vendor Matrix in increasing Order:


array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125]])

In [13]:
vendor_matrix(vector=l,n=6,increasing=False)

Vendor Matrix in decreasing Order:


array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1]])